export const MOCK_PLACES = [{
  "city": {"name": `Brussels`, "location": {"latitude": 50.846557, "longitude": 4.351697, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`],
  "title": `Canal View Prinsengracht`,
  "is_favorite": true,
  "is_premium": false,
  "rating": 3.5,
  "type": `room`,
  "bedrooms": 1,
  "max_adults": 2,
  "price": 136,
  "goods": [`Towels`, `Breakfast`, `Dishwasher`, `Coffee machine`, `Fridge`, `Laptop friendly workspace`, `Washer`, `Air conditioning`, `Baby seat`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country. In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.`,
  "location": {"latitude": 50.867557, "longitude": 4.357697, "zoom": 16},
  "id": 1
}, {
  "city": {"name": `Hamburg`, "location": {"latitude": 53.550341, "longitude": 10.000654, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`],
  "title": `Penthouse, 4-5 rooms + 5 balconies`,
  "is_favorite": false,
  "is_premium": true,
  "rating": 4.3,
  "type": `room`,
  "bedrooms": 1,
  "max_adults": 1,
  "price": 222,
  "goods": [`Breakfast`, `Laptop friendly workspace`, `Air conditioning`, `Baby seat`, `Towels`, `Washer`, `Fridge`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country. In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.`,
  "location": {"latitude": 53.558341000000006, "longitude": 10.001654, "zoom": 16},
  "id": 2
}, {
  "city": {"name": `Paris`, "location": {"latitude": 48.85661, "longitude": 2.351499, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`],
  "title": `The Joshua Tree House`,
  "is_favorite": false,
  "is_premium": true,
  "rating": 3.3,
  "type": `apartment`,
  "bedrooms": 1,
  "max_adults": 5,
  "price": 202,
  "goods": [`Baby seat`, `Dishwasher`, `Laptop friendly workspace`, `Breakfast`, `Washer`, `Towels`, `Air conditioning`, `Fridge`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.`,
  "location": {"latitude": 48.858610000000006, "longitude": 2.330499, "zoom": 16},
  "id": 3
}, {
  "city": {"name": `Hamburg`, "location": {"latitude": 53.550341, "longitude": 10.000654, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`],
  "title": `Beautiful & luxurious apartment at great location`,
  "is_favorite": false,
  "is_premium": false,
  "rating": 2.6,
  "type": `hotel`,
  "bedrooms": 3,
  "max_adults": 9,
  "price": 273,
  "goods": [`Air conditioning`, `Towels`, `Baby seat`, `Washer`, `Breakfast`, `Fridge`, `Laptop friendly workspace`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!`,
  "location": {"latitude": 53.550341, "longitude": 9.980654000000001, "zoom": 16},
  "id": 4
}, {
  "city": {"name": `Cologne`, "location": {"latitude": 50.938361, "longitude": 6.959974, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`],
  "title": `The Pondhouse - A Magical Place`,
  "is_favorite": false,
  "is_premium": false,
  "rating": 3.9,
  "type": `house`,
  "bedrooms": 2,
  "max_adults": 4,
  "price": 181,
  "goods": [`Breakfast`, `Laptop friendly workspace`, `Washer`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `This is a place for dreamers to reset, reflect, and create. Designed with a 'slow' pace in mind, our hope is that you enjoy every part of your stay; from making local coffee by drip in the morning, choosing the perfect record to put on as the sun sets.`,
  "location": {"latitude": 50.945361, "longitude": 6.962974, "zoom": 16},
  "id": 5
}, {
  "city": {"name": `Amsterdam`, "location": {"latitude": 52.37454, "longitude": 4.897976, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`],
  "title": `Tile House`,
  "is_favorite": false,
  "is_premium": true,
  "rating": 3.2,
  "type": `house`,
  "bedrooms": 1,
  "max_adults": 5,
  "price": 115,
  "goods": [`Coffee machine`, `Fridge`, `Dishwasher`, `Laptop friendly workspace`, `Air conditioning`, `Baby seat`, `Breakfast`, `Towels`, `Washer`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.`,
  "location": {"latitude": 52.36854, "longitude": 4.887976, "zoom": 16},
  "id": 6
}, {
  "city": {"name": `Hamburg`, "location": {"latitude": 53.550341, "longitude": 10.000654, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`],
  "title": `Perfectly located Castro`,
  "is_favorite": false,
  "is_premium": false,
  "rating": 4.9,
  "type": `house`,
  "bedrooms": 2,
  "max_adults": 3,
  "price": 997,
  "goods": [`Washer`, `Dishwasher`, `Baby seat`, `Breakfast`, `Air conditioning`, `Fridge`, `Coffee machine`, `Towels`, `Laptop friendly workspace`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country. In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.`,
  "location": {"latitude": 53.538341, "longitude": 9.976654000000002, "zoom": 16},
  "id": 7
}, {
  "city": {"name": `Brussels`, "location": {"latitude": 50.846557, "longitude": 4.351697, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/19.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`],
  "title": `Wood and stone place`,
  "is_favorite": false,
  "is_premium": false,
  "rating": 4.3,
  "type": `room`,
  "bedrooms": 1,
  "max_adults": 2,
  "price": 282,
  "goods": [`Baby seat`, `Washing machine`, `Breakfast`, `Towels`, `Coffee machine`, `Washer`, `Laptop friendly workspace`, `Air conditioning`, `Cable TV`, `Dishwasher`, `Fridge`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.`,
  "location": {"latitude": 50.862556999999995, "longitude": 4.375697, "zoom": 16},
  "id": 8
}, {
  "city": {"name": `Paris`, "location": {"latitude": 48.85661, "longitude": 2.351499, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/9.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/4.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/2.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/14.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/7.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`],
  "title": `Beautiful & luxurious apartment at great location`,
  "is_favorite": false,
  "is_premium": false,
  "rating": 2.9,
  "type": `house`,
  "bedrooms": 2,
  "max_adults": 5,
  "price": 841,
  "goods": [`Air conditioning`, `Fridge`, `Coffee machine`, `Laptop friendly workspace`, `Towels`, `Baby seat`, `Dishwasher`, `Breakfast`, `Washer`, `Washing machine`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.`,
  "location": {"latitude": 48.84761, "longitude": 2.356499, "zoom": 16},
  "id": 9
}, {
  "city": {"name": `Dusseldorf`, "location": {"latitude": 51.225402, "longitude": 6.776314, "zoom": 13}},
  "preview_image": `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`,
  "images": [`https://assets.htmlacademy.ru/intensives/javascript-3/hotel/11.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/13.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/5.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/16.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/17.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/8.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/10.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/18.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/12.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/20.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/15.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/3.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/1.jpg`, `https://assets.htmlacademy.ru/intensives/javascript-3/hotel/6.jpg`],
  "title": `Waterfront with extraordinary view`,
  "is_favorite": false,
  "is_premium": false,
  "rating": 3.8,
  "type": `apartment`,
  "bedrooms": 1,
  "max_adults": 4,
  "price": 209,
  "goods": [`Washer`, `Laptop friendly workspace`, `Towels`, `Baby seat`, `Air conditioning`, `Breakfast`],
  "host": {"id": 25, "name": `Angelina`, "is_pro": true, "avatar_url": `img/avatar-angelina.jpg`},
  "description": `Peaceful studio in the most wanted area in town. Quiet house Near of everything. Completely renovated. Lovely neighbourhood, lot of trendy shops, restaurants and bars in a walking distance.`,
  "location": {"latitude": 51.236402000000005, "longitude": 6.784314, "zoom": 16},
  "id": 10
}];
